package:
  name: miniupnpc
  version: 2.3.3 # renovate: datasource=github-tags depName=miniupnp/miniupnp
  epoch: 1
  description: Lightweight UPnP client library and tools
  copyright:
    - license: BSD-3-Clause

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: upstream-version

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/miniupnp/miniupnp
      tag: miniupnpc_${{vars.upstream-version}}

  - uses: autoconf/make
    with:
      dir: ${{package.name}}

  - uses: autoconf/make-install
    with:
      dir: ${{package.name}}
      opts: INSTALLPREFIX=/usr

  - uses: strip

subpackages:
  - name: miniupnpc-dev
    description: Development files for miniupnpc
    dependencies:
      runtime:
        - miniupnpc=${{package.full-version}}
    pipeline:
      - uses: split/dev
    test:
      environment:
        contents:
          repositories:
            - *wolfi-repository
          keyring:
            - *wolfi-keyring
          packages:
            - busybox
            - ${{package.name}}-dev=${{package.full-version}}
      pipeline:
        - name: Basic test
          runs: |
            test -f /usr/include/miniupnpc/miniupnpc.h
            test -e /usr/lib/pkgconfig/miniupnpc.pc || \
            test -e /usr/share/pkgconfig/miniupnpc.pc

update:
  enabled: true
  github:
    identifier: miniupnp/miniupnp
    use-tag: true
    strip-prefix: miniupnpc_
  version-transform:
    - match: ^([0-9]+)_([0-9]+)_([0-9]+)$
      replace: ${1}.${2}.${3}

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic test
      runs: |
        upnpc --version || \
        upnpc --help
