package:
  name: tautulli
  version: 2.17.2 # renovate: datasource=github-tags depName=Tautulli/Tautulli
  epoch: 0
  description: Monitoring, analytics, and notifications for Plex Media Server
  copyright:
    - license: GPL-3.0-or-later
  options:
    no-depends: true

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - python-3.14

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}/opt/tautulli"

  - uses: fetch
    with:
      strip-components: "1"
      directory: "${{targets.destdir}}/opt/tautulli"
      expected-none: "true"
      uri: https://github.com/Tautulli/Tautulli/archive/refs/tags/v${{package.version}}.tar.gz
      delete: "true"

  - runs: |
      printf '%s\n' master > "${{targets.destdir}}/opt/tautulli/branch.txt"
      printf '%s\n' "v${{package.version}}" > "${{targets.destdir}}/opt/tautulli/version.txt"

  - uses: vegops/rootfs
  # - uses: vegops/prune

update:
  enabled: true
  github:
    identifier: Tautulli/Tautulli
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - busybox
        - python-3.14
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic Tautulli package test
      runs: |
        python /opt/tautulli/Tautulli.py --help >/dev/null
