package:
  name: i2pd
  version: 2.60.0
  epoch: 0
  description: I2P daemon
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - build-base
      - boost-dev
      - git
      - miniupnpc-dev
      - openssl-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PurpleI2P/i2pd
      tag: ${{package.version}}

  - runs: |
      make USE_UPNP=yes -j$(nproc)

      mkdir -p "${{targets.destdir}}/usr/bin"
      cp i2pd "${{targets.destdir}}/usr/bin/i2pd"

      mkdir -p "${{targets.destdir}}/usr/share/i2pd"
      cp -r contrib/certificates "${{targets.destdir}}/usr/share/i2pd/certificates"

      mkdir -p "${{targets.destdir}}/etc/i2pd"
      cp contrib/docker/i2pd-docker.conf "${{targets.destdir}}/etc/i2pd/i2pd.conf"

      # Patch config for container use
      sed -i 's/^log = file/log = stdout/' "${{targets.destdir}}/etc/i2pd/i2pd.conf"
      sed -i 's/^loglevel = none/loglevel = error/' "${{targets.destdir}}/etc/i2pd/i2pd.conf"

  - uses: strip

update:
  enabled: true
  github:
    identifier: PurpleI2P/i2pd
    use-tag: true
    tag-filter-prefix: 2.59.

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic i2pd command test
      runs: |
        i2pd --help >/dev/null 2>&1 || \
        i2pd --version >/dev/null 2>&1
