package:
  name: prowlarr
  version: 2.5.2.5491 # renovate: datasource=github-releases depName=Prowlarr/Prowlarr
  epoch: 0
  description: Indexer manager/proxy built for Usenet and BitTorrent
  copyright:
    - license: GPL-3.0
  options:
    no-depends: true

vars:
  dotnet-sdk-version: "10"

environment:
  environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
    PROWLARRVERSION: "${{package.version}}"
    BUILD_SOURCEBRANCHNAME: "v${{package.version}}"
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - bash
      - build-base
      - busybox
      - dotnet-10-sdk
      - nodejs
      - pnpm
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Prowlarr/Prowlarr
      tag: v${{package.version}}

  - runs: |
      echo '{"sdk":{"version":"${{vars.dotnet-sdk-version}}"}}' > global.json
      sed -i 's#<TreatWarningsAsErrors>true</TreatWarningsAsErrors>#<TreatWarningsAsErrors>false</TreatWarningsAsErrors>#' src/Directory.Build.props

  - runs: |
      case "${{build.arch}}" in
        x86_64)  rid="x64" ;;
        aarch64) rid="arm64" ;;
      esac

      ./build.sh \
        --backend \
        --frontend \
        --packages \
        -f net8.0 \
        -r "linux-${rid}"

  - runs: |
      mkdir -p "${{targets.destdir}}/opt/prowlarr"
      rm -f _output/net*/linux-*/publish/ServiceInstall*
      rm -f _output/net*/linux-*/publish/ServiceUninstall*
      rm -f _output/net*/linux-*/publish/Prowlarr.Update*
      rm -f _output/net*/linux-*/publish/Prowlarr.Windows*
      cp -af _output/net*/linux-*/publish/. "${{targets.destdir}}/opt/prowlarr/"
      cp -af _output/UI "${{targets.destdir}}/opt/prowlarr/"

  - runs: |
      chmod -R 0755 "${{targets.destdir}}"/opt/prowlarr/*

      mkdir -p "${{targets.destdir}}/usr/bin"
      ln -sf /opt/prowlarr/Prowlarr "${{targets.destdir}}/usr/bin/prowlarr"

  - uses: strip

update:
  enabled: true
  github:
    identifier: Prowlarr/Prowlarr
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - busybox
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic Prowlarr package test
      runs: |
        test -x /opt/prowlarr/Prowlarr
        test -L /usr/bin/prowlarr
        test -d /opt/prowlarr/UI
