package:
  name: tor
  version: 0.4.9.5
  epoch: 1
  description: Tor anonymity network
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - build-base
      - ca-certificates
      - curl
      - libevent-dev
      - libseccomp-dev
      - linux-headers
      - openssl-dev
      - xz-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.torproject.org/tpo/core/tor
      tag: tor-${{package.version}}

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --localstatedir=/tor/var \
        --runstatedir=/tor/run \
        --enable-gpl \
        --enable-pic \
        --disable-manpage \
        --disable-html-manual \
        --disable-asciidoc \
        --disable-systemd \
        --with-tor-user=nonroot \
        --with-tor-group=nonroot

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: dotnet/entrypoint

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: tor-

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - runs: |
        tor --version
        test -x /usr/bin/tor-resolve
        test -x /usr/bin/tor-gencert
        test -x /usr/bin/tor-print-ed-signing-cert
        mkdir -p /tor/var /tor/run
        /usr/bin/entrypoint --verify-config
