package:
  name: radarr
  version: 6.0.4.10291 # renovate: datasource=github-releases depName=Radarr/Radarr
  epoch: 1
  description: Movie collection manager for Usenet and BitTorrent users
  copyright:
    - license: GPL-3.0
  options:
    no-depends: true

vars:
  dotnet-sdk-version: "10"

environment:
  environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
    BUILD_SOURCEBRANCHNAME: "v${{package.version}}"
    RADARRVERSION: "${{package.version}}"
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - bash
      - build-base
      - busybox
      - dotnet-10-sdk
      - nodejs
      - pnpm
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Radarr/Radarr
      tag: v${{package.version}}

  - runs: |
      echo '{"sdk":{"version":"${{vars.dotnet-sdk-version}}"}}' > global.json
      sed -i 's#<TreatWarningsAsErrors>true</TreatWarningsAsErrors>#<TreatWarningsAsErrors>false</TreatWarningsAsErrors>#' src/Directory.Build.props

  - runs: |
      case "${{build.arch}}" in
        x86_64)  rid="x64" ;;
        aarch64) rid="arm64" ;;
      esac
      
      ./build.sh \
        --backend \
        --frontend \
        --packages \
        -f net8.0 \
        -r "linux-${rid}"

  - runs: |
      mkdir -p "${{targets.destdir}}/opt/radarr"
      rm -f _output/net*/linux-*/publish/ServiceInstall*
      rm -f _output/net*/linux-*/publish/ServiceUninstall*
      rm -f _output/net*/linux-*/publish/Radarr.Windows*
      cp -af _output/net*/linux-*/publish/. "${{targets.destdir}}/opt/radarr/"
      cp -af _output/UI "${{targets.destdir}}/opt/radarr/"

  - runs: |
      chmod -R 0755 "${{targets.destdir}}"/opt/radarr/*

  - uses: strip

update:
  enabled: true
  github:
    identifier: Radarr/Radarr
    use-tag: true
    tag-filter-prefix: v6.
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - busybox
  pipeline:
    - name: Mock test
      runs: |
        true
