package:
  name: adguard
  version: 0.107.73 # renovate: datasource=github-releases depName=AdguardTeam/AdGuardHome
  epoch: 1
  description: Network-wide ads and trackers blocking DNS server
  copyright:
    - license: GPL-3.0

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - go-1.26
      - gpg
      - gzip
      - make
      - node-gyp
      - nodejs
      - npm
      - python-3.14
      - yarn
      - zip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AdguardTeam/AdGuardHome
      tag: v${{package.version}}

  - runs: |
      sed -i 's|unix.CAP_NET_BIND_SERVICE,|0,|' ./internal/aghnet/net_linux.go
      sed -i 's|unix.PR_CAP_AMBIENT,|unix.PR_CAPBSET_READ,|' ./internal/aghnet/net_linux.go
      sed -i 's|unix.PR_CAP_AMBIENT_IS_SET,|unix.CAP_NET_BIND_SERVICE,|' ./internal/aghnet/net_linux.go
      go mod tidy

  - runs: |
      case "${{build.arch}}" in
        x86_64)  TARGETARCH="amd64" ;;
        aarch64) TARGETARCH="arm64" ;;
      esac

      make \
        OS=linux \
        ARCH="${TARGETARCH}" \
        CHANNEL="release" \
        VERSION="${{package.version}}" \
        SIGN=0 \
        VERBOSE=3 \
        build-release

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      cp -a dist/AdGuardHome_linux_*/AdGuardHome/AdGuardHome "${{targets.destdir}}/usr/bin/AdGuardHome"

  - runs: |
      mkdir -p "${{targets.destdir}}/${{package.name}}/etc"
      mkdir -p "${{targets.destdir}}/${{package.name}}/var"
      mkdir -p "${{targets.destdir}}/${{package.name}}/run"

  - uses: strip

update:
  enabled: true
  github:
    identifier: AdguardTeam/AdGuardHome
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic AdGuard command test
      runs: |
        AdGuardHome --version >/dev/null 2>&1 || \
        AdGuardHome --help >/dev/null 2>&1
