package:
  name: lnd
  version: 0.20.1_beta # renovate: datasource=github-tags depName=lightningnetwork/lnd
  epoch: 1
  description: Lightning Network Daemon
  copyright:
    - license: MIT

var-transforms:
  - from: ${{package.version}}
    match: _
    replace: "-"
    to: upstream-version

environment:
  environment:
    GOPATH: /tmp/go
    CGO_ENABLED: "0"
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - go-1.26
      - gpg
      - gpg-agent
      - wget

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lightningnetwork/lnd
      tag: v${{vars.upstream-version}}

  - runs: |
      wget -qO roasbeef.asc "https://raw.githubusercontent.com/lightningnetwork/lnd/master/scripts/keys/roasbeef.asc"

      export GNUPGHOME="$(mktemp -d)"
      trap 'rm -rf "$GNUPGHOME"' EXIT

      gpg --import roasbeef.asc
      
      git verify-tag "v${{vars.upstream-version}}"

  - runs: |
      make release-install

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      mkdir -p "${{targets.destdir}}/usr/share/lnd"
      cp /tmp/go/bin/lncli "${{targets.destdir}}/usr/bin/lncli"
      cp /tmp/go/bin/lnd   "${{targets.destdir}}/usr/bin/lnd"
      cp sample-lnd.conf "${{targets.destdir}}/usr/share/lnd/lnd.sample.conf"

  - uses: dotnet/entrypoint

  - uses: strip

update:
  enabled: true
  github:
    identifier: lightningnetwork/lnd
    use-tag: true
    strip-prefix: v
  version-transform:
    - match: "-"
      replace: _

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic test
      runs: |
        lnd --version >/dev/null 2>&1 || \
        lnd --help >/dev/null 2>&1
        lncli --version >/dev/null 2>&1 || \
        lncli --help >/dev/null 2>&1
