package:
  name: electrs
  version: 0.11.1 # renovate: datasource=github-tags depName=romanz/electrs
  epoch: 2
  description: An efficient re-implementation of Electrum Server in Rust
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - clang-18
      - lz4-dev
      - lz4-static
      - openssl-static
      - pkgconf
      - rocksdb-10
      - snappy-dev
      - snappy-static
      - zlib-dev
      - zlib-static
      - zstd-dev
      - zstd-static
  environment:
    ROCKSDB_INCLUDE_DIR: /usr/include
    ROCKSDB_LIB_DIR: /usr/lib
    ROCKSDB_STATIC: "1"
    SNAPPY_LIB_DIR: /usr/lib
    SNAPPY_STATIC: "1"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/romanz/electrs
      tag: v${{package.version}}

  - uses: cargo/build
    with:
      output: electrs
      opts: |
        --release \
        --locked \
        --bin electrs \
        --features metrics_process
      rustflags: >-
        -C link-arg=-Wl,-Bstatic
        -C link-arg=-lz
        -C link-arg=-lsnappy
        -C link-arg=-Wl,-Bdynamic

  - runs: |
      install -Dm644 doc/config_example.toml "${{targets.destdir}}/usr/share/electrs/config.example.toml"

  - uses: dotnet/entrypoint

  - uses: strip

update:
  enabled: true
  github:
    identifier: romanz/electrs
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - busybox
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic electrs command test
      runs: |
        test -x /usr/bin/electrs
        electrs --version >/dev/null 2>&1
