package:
  name: bitcoin-core
  version: 31.0 # renovate: datasource=github-tags depName=bitcoin/bitcoin
  epoch: 1
  description: Bitcoin Core daemon
  copyright:
    - license: MIT

environment:
  environment:
    BITCOIN_GENBUILD_NO_GIT: "1"
  contents:
    repositories:
      - &wolfi-repository https://packages.wolfi.dev/os
    keyring:
      - &wolfi-keyring https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - build-base
      - cmake
      - linux-headers
      - pkgconf
      - libevent-dev
      # Temporary pin until bitcoin builds are compatible with Boost 1.91 in Wolfi.
      - boost-dev=1.90.0
      - boost-static=1.90.0
      - boost-tools=1.90.0
      - zeromq-dev
      - libzmq-static
      - gpg
      - gpg-agent
      - curl
      - jq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bitcoin/bitcoin
      tag: v${{package.version}}

  - runs: |
      export GNUPGHOME="$(mktemp -d)"
      trap 'rm -rf "$GNUPGHOME"' EXIT

      curl -s "https://api.github.com/repos/bitcoin-core/guix.sigs/contents/builder-keys" | jq -r '.[].download_url' | while read url; do curl -s "$url" | gpg --import; done

      git verify-tag "v${{package.version}}"

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_BITCOIN_BIN=OFF \
        -DBUILD_DAEMON=ON \
        -DBUILD_GUI=OFF \
        -DBUILD_CLI=ON \
        -DBUILD_TX=ON \
        -DBUILD_UTIL=OFF \
        -DBUILD_UTIL_CHAINSTATE=OFF \
        -DBUILD_WALLET_TOOL=OFF \
        -DENABLE_WALLET=OFF \
        -DENABLE_IPC=OFF \
        -DENABLE_EXTERNAL_SIGNER=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_GUI_TESTS=OFF \
        -DBUILD_BENCH=OFF \
        -DBUILD_FUZZ_BINARY=OFF \
        -DBUILD_FOR_FUZZING=OFF \
        -DBUILD_KERNEL_LIB=OFF \
        -DWITH_ZMQ=ON \
        -DWITH_USDT=OFF \
        -DWITH_QRENCODE=OFF \
        -DWITH_DBUS=OFF \
        -DREDUCE_EXPORTS=ON \
        -DWERROR=OFF \
        -DWITH_CCACHE=OFF \
        -DINSTALL_MAN=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: bitcoin/bitcoin
    use-tag: true
    tag-filter-prefix: v30.
    strip-prefix: v

test:
  environment:
    contents:
      repositories:
        - *wolfi-repository
      keyring:
        - *wolfi-keyring
      packages:
        - apk-tools
        - busybox
        - posix-libc-utils
        - ${{package.name}}=${{package.full-version}}
  pipeline:
    - name: Basic bitcoin command test
      runs: |
        bitcoind --version
        bitcoin-cli --version
        bitcoin-tx --version
