contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - wolfi-baselayout
    - ca-certificates-bundle
    - tzdata
    - prometheus-minimal

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: "65532"

entrypoint:
  command: /usr/bin/entrypoint

work-dir: /

volumes:
  - /prometheus/etc
  - /prometheus/var

paths:
  - path: /prometheus
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o700
  - path: /prometheus/etc
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o700
  - path: /prometheus/etc/rules
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o700
  - path: /prometheus/var
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o700

annotations:
  org.opencontainers.image.title: "prometheus-minimal"
  org.opencontainers.image.description: "Hardened Minimal Prometheus monitoring server image built on Wolfi with daily CVE patches"
  org.opencontainers.image.url: "https://github.com/vegops/containers"
  org.opencontainers.image.source: "https://github.com/vegops/containers/tree/main/prometheus-minimal"
  org.opencontainers.image.licenses: "Apache-2.0"

archs:
  - x86_64
  - aarch64

layering:
  strategy: origin
